export const Button = {
  defaultProps: {
    fontFamily: "Montserrat",
  },
  sizes: {
    mini: {
      px: '10px',
      py: '8px',
      gap: '4px',
      fontSize: "sm",
      fontWeight: "600",
      lineHeight: "20px",
      borderRadius: "8px",
      height: "36px",
      _before: {
        borderRadius: "8px",
      },
    },
    sm: {
      fontSize: "md",
      fontWeight: "600",
      lineHeight: "22px",
      borderRadius: "20px",
      _before: {
        borderRadius: "20px",
      },
      height: "38px",
    },
    md: {
      fontSize: "md",
      fontWeight: "600",
      lineHeight: "22px",
      borderRadius: "10px",
      _before: {
        borderRadius: "10px",
      },
      height: "42px",
    },
    lg: {
      fontSize: "xl",
      fontWeight: "600",
      lineHeight: "26px",
      borderRadius: "12px",
      _before: {
        borderRadius: "12px",
      },
      height: "50px",
    },
  },
  variants: {
    outline: {
      backgroundColor: "gray.600",
      color: "gray.20",
      position: "relative",
      border: "none",
      _before: {
        content: "''",
        position: "absolute",
        top: "-1px",
        left: "-1px",
        right: "-1px",
        height: "calc(100% + 3px)",
        width: "calc(100% + 2px)",
        background: "var(--chakra-colors-primaryRadial)",
        zIndex: -1,
      },
      _focus: {
        bg: "glassBackground",
        border: "1px solid",
        borderColor: "blue",
        boxShadow:
          "0px 1px 0px 0px var(--chakra-colors-cyan), 0px 0px 0px 0px #6E81EE52",
        _before: {
          display: "none",
        },
      },
      _disabled: {
        boxShadow: "0px 2px 0px 0px var(--chakra-colors-cyan)",
        backgroundImage: "glassBackground",
        opacity: 0.4,
        _before: {
          content: "''",
          position: "absolute",
          top: "-1px",
          left: "-1px",
          right: "-1px",
          height: "calc(100% + 3px)",
          width: "calc(100% + 2px)",
          background: "var(--chakra-colors-primaryRadial)",
          opacity: 0.4,
          zIndex: -1,
        },
      },
      _hover: {
        bg: "rgba(110, 129, 238, 0.32)",
        border: "1px solid",
        borderColor: "blue",
        boxShadow:
          "0px 1px 0px 0px var(--chakra-colors-cyan), 0px 0px 0px 0px #6E81EE52",
        _before: {
          display: "none",
        },          
      },
    },
    solid: {
      bg: "var(--chakra-colors-primaryRadial)",
      color: "gray.20",
      _before: {
        content: "''",
        position: "absolute",
        top: "-0px",
        left: "-1px",
        right: "-1px",
        height: "calc(100% + 2px)",
        width: "calc(100% + 2px)",
        background: "var(--chakra-colors-cyan)",
        zIndex: -1,
      },
      _hover: {
        backgroundColor: "blue",
      },
      _focus: {
        backgroundColor: "blue",
      },
      _disabled: {
        boxShadow: "0px 2px 0px 0px var(--chakra-colors-cyan)",
        opacity: "0.4",
        position: "relative",
        bg: "var(--chakra-colors-primaryRadial)",

        _before: {
          content: "''",
          position: "absolute",
          top: "-0px",
          left: "-1px",
          right: "-1px",
          height: "calc(100% + 2px)",
          width: "calc(100% + 2px)",
          background: "var(--chakra-colors-primaryRadial)",
          zIndex: -1,
          opacity: 0.4,
        },
      },
    },
    gray: {
      backgroundColor: "gray.500",
      color: "gray.20",
      borderStyle: "solid",
      borderTopWidth: "1px",
      borderRightWidth: "1px",
      borderLeftWidth: "1px",
      borderBottomWidth: "2px",
      borderColor: "gray.400",
      _hover: {
        bg: "gray.400",
      },
      _focus: {
        bg: "gray.400",
      },
      _disabled: {
        backgroundColor: "gray.700",
        boxShadow: "0px 2px 0px 0px var(--chakra-colors-gray-400)",
      },
    },
    ghost: {
      background: "transparent",
      backgroundImage: "var(--chakra-colors-primaryLinear)",
      backgroundClip: "text",
      _hover: {
        color: "blue",
        background: "transparent",
      },
      _focus: {
        color: "blue",
        background: "transparent",
      },
      _disabled: {
        background: "transparent",
        backgroundImage: "var(--chakra-colors-primaryLinear)",
        backgroundClip: "text",
      },
    },
    rightAnswer: {
      background: "rgba(93,210,122, 0.2)",
      color: "gray.0",
      borderStyle: "solid",
      borderTopWidth: "1px",
      borderRightWidth: "1px",
      borderLeftWidth: "1px",
      borderBottomWidth: "2px",
      borderColor: "green.400",
    },
    wrongAnswer: {
      background: "rgba(255, 98, 89, 0.2)",
      color: "gray.0",
      borderStyle: "solid",
      borderTopWidth: "1px",
      borderRightWidth: "1px",
      borderLeftWidth: "1px",
      borderBottomWidth: "2px",
      borderColor: "red.400",
    },
    default: {
      background: "var(--chakra-colors-glassBackground)",
      color: "gray.0",
      borderStyle: "solid",
      borderTopWidth: "1px",
      borderRightWidth: "1px",
      borderLeftWidth: "1px",
      borderBottomWidth: "2px",
      borderColor: "gray.400",
      sx: { cursor: "default" },
      _disabled: {
        opacity: "0.50",
      },
    },
    glassBackgroundDisabled: {
      bg: "var(--chakra-colors-glassBackground)",
      color: "gray.0",
      borderStyle: "solid",
      borderTopWidth: "1px",
      borderRightWidth: "1px",
      borderLeftWidth: "1px",
      borderBottomWidth: "2px",
      borderColor: "gray.400",
      opacity: "0.50",
    },
    pressed: {
      backgroundColor: "rgba(256, 256, 256, 0.2)",
      color: "gray.0",
      borderStyle: "solid",
      borderTopWidth: "1px",
      borderRightWidth: "1px",
      borderLeftWidth: "1px",
      borderBottomWidth: "2px",
      borderColor: "gray.0",
    },
  },
};
